function createfigure_anomaly(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 23-Nov-2020 09:54:42

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
colororder([0 0.447 0.741]);

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'DisplayName','Vertical Displacement');

% Create ylabel
ylabel({'Vertical Displacement [m]'});
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.0224539877300613 0.117546012269939]);

% Set the remaining axes properties
set(axes1,'YColor',[0 0.447 0.741]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(X1,Y2,'DisplayName','Z-axis Wheel-Rail Contact Point Acceleration');

% Create ylabel
ylabel({'Acceleration [m/s^2]'});
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-20 10]);

% Set the remaining axes properties
set(axes1,'YColor',[0.85 0.325 0.098]);
% Create xlabel
xlabel({'Position [m]'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 35]);
box(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

% Create colorbar
colorbar(axes1);

% Create arrow
annotation(figure1,'arrow',[0.146755162241888 0.1976401179941],...
    [0.825190476190476 0.852380952380953]);

% Create textbox
annotation(figure1,'textbox',...
    [0.209439528023599 0.871490049435311 0.131637164438281 0.0417956648504033],...
    'String',{'Wielding Joint Anomaly'});

% Create arrow
annotation(figure1,'arrow',[0.491150442477876 0.443215339233038],...
    [0.246619047619048 0.357142857142857]);

% Create textbox
annotation(figure1,'textbox',...
    [0.367256637168142 0.402442430387692 0.0969763985096003 0.0417956648504033],...
    'String',{'Rail Corrugation'});

