function createfigure_aba_sim(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-Nov-2020 10:08:11

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot1 = plot(X1,Y1,'DisplayName','Z-Axis Acceleration');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,316.109526266747,994.233113033786);
% Create datatip
datatip(plot1,'DataIndex',241077);

% Create ylabel
ylabel({'Z-Axis Acceleration of Axle-Box [m/s^2]'});

% Create xlabel
xlabel({'Time [s]'});

% Create title
title({'ABA (Axle-Box Acceleration) z-axis vs Time in Quarter Car Model'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[309.484412954061 322.417947830414]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-2318.05656685082 2313.1590587036]);
box(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

